### ISSUE TITLE
K3.0 - Guests cannot post, even when Security is set to "Yes"

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#1503]
Even when "Allow Guests to Post/Write" is set to Yes in the Config, a user that is not logged in cannot post.

**Comment by Luciana2001** [comment]
HSV 1 LATEST CURE
I contacted my HSV 1 from my fiancee, I discovered little sore on my lip, I taught it was normal skin irritation not knowing it was sign of Herpes virus. I went for a test and my result came out positive and I was told by my doctor that there was no cure yet. Which really affected my life, because of the stigma the virus carries. I was using  Famvir drugs which reduces the outbreaks for a period of time but it is not a total cure. I came across a testimony on you tube about a lady that was cured from Genital herpes by Dr. Ahmed Usman Herbal Medicine. I showed the testimony to my fiancee who discouraged me for contacting the doctor. But because I was so desperate to cure mine I contacted Dr. Ahmed with the email I found on the testimony, which he replied minutes later and asked me the type of HSV I have. After much discussion he decided to call me so that I won't feel he is a scammer. He sent the Herbal Medicine to my country which I took for two weeks with the doctor prescription. The sores in my lip was gone and I felt different. So I went for a check-up and my result came out negative. My fiancee was surprised and he ordered for his Medicine too from Dr. Ahmed which he is taking recently. Please don't let anyone discouraged you. No harm in trying. This is Doctor Ahmed Usman email address; drahmedusman5104@gmail.com or  Whatsapp +2348064460510. He has cure for any type of infections.
