### ISSUE TITLE
[develop] Crypsis: custom.less should be loaded last (otherwise she will overwritten again)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3037]

**Comment by 810** [comment]
fixed and merged

**Comment by Ruud68** [comment]
Hi, in order to NOT (accidentally) overwrite the custom.less with a new version of Kunena it is better to place that file not in ./components/com_kunena/template/crypsis/less but in ./media/kunena (as mentioned in remarks in crypsis.less)

The @import line should then read: @import '../../../../../media/kunena/custom.less';

hope this helps :)
