### ISSUE TITLE
Topic Icons - Global Setting (in addition to local per Category)

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#3164]
Topic Icons can currently be set per category, which is a very welcome feature.  However, it needs to be set for each category by hand.

It would be nice if there was a global setting as well, that could then be overridden by per-category, if needed, so that new categories do not need to be set by hand as they are created.  (Similar to "Default category icon" in Crypsis, and how it can be changed per category in Category Manager.)

**Comment by GJSchaller** [comment]
This can be done by using /components/com_kunena/template/blue_eagle/images/topicicons/system - I am OK with closing this request, if this works.

**Comment by sozzled** [comment]
Does this also address #3251 ?

**Comment by GJSchaller** [comment]
This is for Topics, not Categories, so I would say no.  Topic Icons are presented as images, Category icons as CSS, from what I can tell, so they are two different systems.

**Comment by sozzled** [comment]
#3251 concerns ***topic icons*** (set on a per-category basis).  This topic #3164 concerns ***topic icons***, "globally" for all categories.  You stated at the beginning "Topic Icons can currently be set per category, which is a very welcome feature."  The problem is that the *Category Manager* settings do not work with *Blue Eagle".  You stated at the beginning "Topic Icons can currently be set per category, which is a very welcome feature."  The point I am trying to make is that this statement is untrue for "Blue Eagle* and ***all*** templates derived from it.

I can see that there are two different systems:  one system for Crypsis and another system for everything else.

I am not discussing category icons.  Does this help clarify my involvement/input with this topic?

**Comment by GJSchaller** [comment]
Ah, misread.

In that case, no, the two issues are unrelated.  This is specifically for an all-or-nothing setting (which is resolved), the opposite of a per-category setting.
