### ISSUE TITLE
Check Subscription Box already checked on reply even if "Check Subscription Box" is set to  "No" in Check Subscription parameters

### ISSUE THREAD

**Issue by oliviercpl** [Kunena/Kunena-Forum#3728]
#### Steps to reproduce the issue

In parameter "Subscription" set "Check Subscription Box" to "no" and "Topic Subscriptions" to "E-mail first update"

Reply to a post
#### Expected result

The check box "Subscribe to this post" is not checked
#### Actual result

The check box "Subscribe to this post" is checked
#### System information (as much as possible)

Joomla version:  3.4.8
Kunena version: 4.0.10
Php version: 5.4.14
Database version: 5.6.12

**Comment by sozzled** [comment]
This is a known issue and it has been discussed on the forum many times.

The issue was created by a change (an "enhancement") added in K 4.0.5 by the developers.  I wrote about this issue in http://www.kuneze.com/blog/40-kunena-4-0-5-changed-subscribe-checkbox-behaviour-angers-community

You can also see more about this issue in #3541

**Comment by 810** [comment]
Then the user setting is different. 
You can reset it for user profile by adding this code on your database

```
UPDATE `#__kunena_users` SET `canSubscribe` = '-1'
```

 change #_ with your prefix

We haven't included this, because else user setting will be lost on users. So its a choice 1) user must change the setting, on his user profile. Or 2) Administrator can set default setting for everyone by the database change.

Im closing this issue.
