### ISSUE TITLE
Auto Load Bootstrap css

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4914]
#### Steps to reproduce the issue
1. Install joomla 3.6.4 with a non bootstrap template
2. Install Kunena 4.0.12
3. Update kunena to 5.0.3

#### Expected result
Auto Load Bootstrap css for non bootstrap templates.
This auto detect should be included in the installation package (During update process or new installation) to avoid further inconvenience and frustration for users

#### Actual result
The user must load bootstrap css manually if using a non bootstrap template.
Crypsis -> Basic Settings -> Load Bootstrap css

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.3
Php version: 7.0.12
Database version: 5.6.33

#### Additional comments
This is making a lot of noise in the forum.
People often think that crypsis and crypsisb3 are broken in 5.0.x

**Comment by 810** [comment]
we can't include it, because there are other frameworks with the same css classes and code, like gantry.

if we enable the option, other users are complaining with different kind of bootstrap versions.

There are always user that will complain, most issues can be fixed by enable the option, On big releases you should always check the config/template options.

**Comment by sshcli** [comment]
At least a warning should be visible.
