### ISSUE TITLE
Kunena - smart search no result on search

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#5304]
#### Steps to reproduce the issue

enable smart search, and enable kunena search plugin and finder.

Create a new topic, the subject is added on the smart search, see backend.
Then try to search the topic by the smart search module.

#### Expected result

Subject found

#### Actual result

No Results Found

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by JoshJourney** [comment]
Tested with a fresh install of the latest version of Joomla and PHP (stable release) and have the same issue. Same result with smart search menu item. On my non fresh Joomla install EasySocial's search is able to pull the data from smart search but has the wrong path ("/component/kunena/" instead of "forum/").

Hoping this gets resolved in Kunena 5.0.11.

**Comment by 810** [comment]
fixed on 5.1

**Comment by sitte** [comment]
I updated (on test installation) Kunena to 5.1.0 and "Kunena - Finder Integration" to 5.1, I enabled plugins. In indexer I cleared results and reindexed all, I can see results from forum posts but in frontend thre is no "forum post area" and search does not show forum posts: http://5.sitte.pl/szukaj
![wyszukiwarka_indeksowanie_tresci_-_test_5_-_zaplecze_-_2018-06-05_15 11 32](https://user-images.githubusercontent.com/10048887/40978008-c9e0204c-68d2-11e8-8a54-a4ff839bca20.jpg)
