### ISSUE TITLE
Open Graph image is missing

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5311]
#### Steps to reproduce the issue
Create a new topic and share it in social networks.

#### Expected result
Every shared topic should have an image.
What image must be used?
Use picture in message content [img][/img]
else
Use attached picture
else
Use category image (This option doesn't exist yet)
else
Use custom image defined in backend (This option doesn't exist yet)
else
Use site logo
else
Use avatar

#### Actual result
Not all shared topics have an image, this is because Open Graph image is not available in kunena.

The following line is missing in /components/com_kunena/controller/topic/item/display.php (Line 383) :
`$doc->setMetaData('og:image', 'example.com/image.png', 'property');`

#### System information (as much as possible)

Joomla version: 3.6.5 and 3.7.0-rc3 dev
Kunena version: 5.0.8-dev
Php version: 7.1.3
Database version: MySQL 5.6.35
 
#### Additional comments
Tested with:
Google+
LinkedIn
Facebook
WhatsApp Web

**Comment by Ruud68** [comment]
Hi, if you want to do it right, then you must also check the image size. Facebook has a minimum size for OpenGraph images. currently that is 200 px (height or width), so if these size conditions are not met, facebook will not use them and will search for its own (fitting) image on the page.
I realize this is not an option, this because of the speed penalty involved in checking image sizes.
That is the reason I myself use a custom (fallback) image as default og: image for Kunena
