### ISSUE TITLE
can't save avatar

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#5846]
#### Steps to reproduce the issue

edit avatar on k.org

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by Sophist-UK** [comment]
Had this same or similar issue with one of my users - turned out that avatars have a standard filename, and the file had indeed been replaced, but it was being cached by the user's browser.

I would say that a fix would be useful - perhaps by adding a random number to the filename.

Of course that may not be the issue here.

**Comment by 810** [comment]
i needed to clear cloudflare cache to see the changes.

**Comment by Sophist-UK** [comment]
Same issue then.
