### ISSUE TITLE
Remove subscriptions when perm block from site 

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5945]
**Is your feature request related to a problem? Please describe.**
The problem is that when you permanent block a user at site level (not forum) they still receive email notifications from topic and category subscriptions. 

The blocked users can't remove those subscriptions because they don't have access anymore.

**Describe the solution you'd like**
When a user is permanent blocked from at site level (not forum level)
All topics and categories subscriptions should be removed automatically 
or
You should add a new checkbox to preform this task, so moderators can check this option when blocking 
or
You should add a new checkbox to preform this task and leave it checked by default.
The moderators can uncheck the box if they want.
 
**Screenshots**
![remove](https://user-images.githubusercontent.com/12942731/40496052-d12ff876-5f46-11e8-926e-f03937693e6b.PNG)

**Comment by Sophist-UK** [comment]
IMO this should be a second layer of defence.

The first layer of defence should be to stop sending subscription emails to anyone who is blocked for the duration of their block. When the block is removed the subscriptions would then restart automatically.

This PR should then be a more severe action, removing subscriptions permanently either because the block is permanent and you don't want them counting towards subscription counts or in order to punish the user by making them resubscribe when the block is lifted.

P.S. Ideally subscriptions should also not be sent to users who access rights to a post or forum have been removed.

P.P.S. Ideally blocked user or users who no longer have access rights would be automatically excluded from any subscription counts.

**Comment by 810** [comment]
The subscription now only checks the accesstype from category and check if the user can access it.
We need to add also a check to block lifetime bans.

**Comment by sshcli** [comment]
Ok,
After several tests, seems like this problem does not exist in J.3.8.10 + K5.1.2-DEV_2018-07-01

As admin, you can still see the subscriptions in the backend, but the blocked user does not receive any mail.

I'm closing this right now.
