### ISSUE TITLE
Primary text labels always change to [Question] when Topic is Sticky or Locked

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6194]
**Describe the bug**
https://www.kunena.org/forum/k5-1-support/156440-primary-text-labels-always-change-to-question-when-topic-is-sticky-or-locked

**To Reproduce**
1. Use default setting "Selectable Topic Icons = Yes"
2. Choose "Show Labels = Topic id"
3. Mark a topic as Sticky (or Locked)
4. Try to change the label

**Expected behavior**
It should switch automatically to the "Important" (or locked) label. At least it should be able to be changed it manually.

**Actual result**
It changes to the label "Question" and it's not possible to use another label.

**Screenshots**

**System information (please complete the following information)**

Joomla version: 
Kunena version:
Php version:
Database version:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ruud68** [comment]
Hi, just installed 5.1.9 and now I experience the same behaviour. Not sure if this PR made it into 5.1.9 (change log is empty)...
Reverting back to 5.1.8 solves the problem.

![peek 2019-02-19 09-32](https://user-images.githubusercontent.com/2733197/53000945-caaab780-3429-11e9-9a0f-de785b742ef6.gif)

**Comment by xillibit** [comment]
I re-open the issue, if it re-appear

**Comment by Ruud68** [comment]
Hi,
the 'feature' of changing the labels to question on locked topics is introduced by this change:
https://github.com/Kunena/Kunena-Forum/commit/dab6ee510e54d584cee41cc680ae5dfc6aa2e4a8

When reverting this change, the issue is solved and when locking a topic, the original topic label is displayed.
I have no idea as to why this change was done.
for me this is blocking as the labels are used in my support 'system', locking a topic and changing the label on that topic to question breaks that 'system'.

So I guess that if this change is a result of a feature request, then at least make it a config setting: change label when locked/stocky 'yes/no'
