### ISSUE TITLE
The email symbol should be visible for admins and global mods

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6863]
**To Reproduce**
Login as admin or global mod and go in a user profile

**Expected behavior**
The email symbol should be visible for admins and global mods, indifferent which setting

**Actual result**
The symbol is hidden

**Comment by xillibit** [comment]
I have tried by login in admin and visiting a normal user profile but i can see the email symbol

I have noticed on kunena.org that email symbol has disappear, in my local installation i can see it:

![image](https://user-images.githubusercontent.com/876395/87427290-dd0a3000-c5e0-11ea-8892-27c85b0d952d.png)

P.S. : the issue seems appear since this change https://github.com/Kunena/Kunena-Forum/issues/6831

**Comment by rich20** [comment]
Rendering Error in layout User/Profile: Property "candisplaymail" is not defined in .../components/com_kunena/template/crypsis/layouts/user/profile/default.php on line 155
Layout was rendered in .../components/com_kunena/template/crypsis/layouts/topic/item/message/default.php on line 23

**Comment by xillibit** [comment]
Fixed with my last change

**Comment by rich20** [comment]
- [x] Success
