### ISSUE TITLE
Upload avatar not saving the image

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#7709]
Tested on Php 8.0

The avatar is showed on the preview, after save, you don't see the avatar on the menu.

The image is missing on media\kunena\avatars\resized\size20\users\

**Comment by sshcli** [comment]
I have seen this problem too (in 5.1)
I believe it is not a real bug, it only needs a progress bar to indicate when the upload process is complete

The problem is that the avatar shows the preview, even if  the image is not totally uploaded. 
This give you a false idea of the upload process, and it incites you you to  click the save button, even when the image has not been totally uploaded  yet.

if it is not possible to implement a progress bar, Another solution could be to disable the save button until the image  has been uploaded 100%.

The best solution is to implement both: Progress bar + Disable save button until process is complete

**Comment by xillibit** [comment]
By looking the code which handle the avatar upload, the avatar file is only copied in the following directory : \jooma\media\kunena\avatars\users\

I will look to fix that

**Comment by 810** [comment]
Looks its correct, only there is some cache issue, when i switch back to 7.4 the avatar is correctly, also after going back to 8.0.

So there is some kind off issue with cache.

**Comment by xillibit** [comment]
Try to check with : https://github.com/joomla/joomla-cms/pull/31554
