### ISSUE TITLE
PHP8.0 install internal server error 500

### ISSUE THREAD

**Issue by nightw0lv** [Kunena/Kunena-Forum#7756]
**Describe the bug**
i upgraded php and i get this message 

**To Reproduce**
ubuntu 20, apache2, php8.0 from php7.4

**Screenshots**
http://prntscr.com/vzi52z
http://prntscr.com/vzi7pj

**System information (please complete the following information)**

Joomla version: 3.10.0-alpha3
Kunena version: 5.1.19
Kunena template name and version: Crypsis 5.1.19
Php version: 8.0
Database version: mariadb10.5.6

**Comment by nightw0lv** [comment]
noticed in database each time i refresh page this comes up
{"type":64,"message":"Array and string offset access syntax with curly braces is no longer supported","file":"\/var\/www\/html\/forum\/libraries\/vendor\/leafo\/lessphp\/lessc.inc.php","line":749}
its from deprecation this changes on the curly braces fixes the error https://github.com/joomla/joomla-cms/issues/30569

**Comment by markfilan** [comment]
This is a ‘catch-all’ error generated by the Web server. The first thing you need to know about an “Internal Server Error” is that the error can only be resolved by fixes to the Web server software. It is not a client-side problem meaning that the problem is not with your browser, your computer, or your internet connection. [500 Internal Server Error](http://net-informations.com/q/mis/500.html) response code indicates that the server encountered an unexpected condition that prevented it from fulfilling the request. However, there are often ways to quickly get around the problem:

- Very commonly, incorrect permissions on a file or folder that contains one of the scripts causes this this error.
- Reload your browser (press F5) or try with another one. The chances that the page will load when you refresh your browser are low, but still, it’s worth giving it a try.
- Try to clear your browser cache. If the page that shows 500 error is cached, after the cache is cleared, the browser will request a new version of the page.
- Come back later. The webmaster may fix the server issue in the meantime.
- A Coding Error in .htaccess. While not as common, be sure to check that your site’s .htaccess file is properly structured.
- Contact the website owners. The last remaining option is to get in touch with the person responsible for maintaining the website.
-
