### ISSUE TITLE
can't reorder discussion categories

### ISSUE THREAD

**Issue by SpudGunMan** [Kunena/Kunena-Forum#8607]
I can't reorder the discussion categories, looks like the dots are there to grab to reorder but out of place and something is wonk can't grab them to reorder.

beta6 rev 5
PHP 7.4.23/Apache/litespeed
Joomla! 4.0.4
Safari/605.1.15
Joomla template: CASSIOPEIA
Kunena template: Aurelia

**Comment by Ruud68** [comment]
can confirm this issue on Kunena 6.0.1.1
noticed that ordering, either by clicking on the column headers or via the order dropdown doesn't work either. maybe related

**Comment by xillibit** [comment]
@Ruud68 : do-you have an idea how to fix it ?

**Comment by Ruud68** [comment]
Hi,
I am in dubio here. CategoriesModel is the only (administrator) model that doesn't extend a Joomla model, that is the reason why sorting (which depends on ListModel) doesn't work.
I have tried to change KunenaModel to extend ListModel (which in turn extends BasedataseModel so that should work) so we can change the view to a Joomla view (with a filter_categories.xml), search bar (which has the javascript in it), etc.
But running into one issue into the other (and not knowing if changing the KunenaModel will change front-end behavior as that model is used on both admin and site)

So if we want to go this route (the Joomla 4 route) then this is probably what needs to be refactored. com_content > categories could be used as a boilerplate.

If we do not want to go that route, we need to fix this issue probably by a combo of JS / php (redoing some of the ListModel / searchbar logic). IMO this is wasted energy as these administrator views should be implemented in a J4 (view and tmpl) way and not as they currently are...

I am leaving on holidays and not sure what awaits in workload after the holidays (september) so cannot be of much use here :(

For my customer who has the ordering issue for categories i am going to set the order in the table directly.

**Comment by xillibit** [comment]
KunenaModel class define some methods specific and some variables for Kunena so replacing it by ListModel it's need then to put in each model extending KunenaModel the methods. I can just change for now the extends of the CategoriesModel to ListModel

**Comment by Ruud68** [comment]
it is more then that, for filtering and sorting rto work the J4 way, the ListModel must be followed. That means also refactoring building the query (function getListQuery, getItems) the current model does this with its own model pulling in the filter fields etc. (function getAdminCategories) and probably we are then only scratching the surface of what needs to be refactored.

My advice is to start new with com_content categories as boilerplate (note that you cannot follow that to the letter as com_content categories allow for multiple nesting where kunena category only allows for one level of nesting (section > category) and when that is basically working re-add specific functionality.

well actually my advice is to start with something simpler: e.g. ranks / rank and refactor the view / model / controller for this: see what you run into and learn for the next.

Kunena is carrying a lot of 'history' dating back from pre J2.5. That makes it difficult to know what and why code is where it is at.

**Comment by Ruud68** [comment]
@xillibit I have done a quick branch on my fork for ranks: https://github.com/Ruud68/Kunena-Forum/tree/refactor-ranks-j4

this has a fully functional ranks controller / model / view / table

Note the rank controller / model / view is not working with this change. Also I think that uploading a rank image should be part of the add/edit rank view, not of the ranks view

**Comment by xillibit** [comment]
I will try to improve it, can-you make a PR please against the K6.1 branch ?

**Comment by Ruud68** [comment]
sorry @xillibit but I cannot do that as I do not have a J4.2.0-dev site to test this with. No time left, leaving on holidays :)

**Comment by xillibit** [comment]
@Ruud68 : i have ported your changes on K6.1 and added missing parts in controllers : https://github.com/Kunena/Kunena-Forum/commit/00b7371d2441060b6cf8f0ce5391a61dd83ebb60

**Comment by Leen29** [comment]
I can confirm this issue on Kunena  6.0.2 2022-08-15  still exists

**Comment by Zarek1989** [comment]
I can confirm this issue on Kunena 6.0.4 | 2022-10-30 still exists.

**Comment by SteveVyse** [comment]
I'm running 6.0.8 2023-01-17 and cannot reorder categories. Work around is altering database table directly.

**Comment by vigalent** [comment]
Still an issue in 6.0.10 (2023-04-02). Will this be fixed, or is there a fix. Batch tools also not working

**Comment by MAD-King** [comment]
Wow, 1 1/2 years later and this bug/issue still exists. 
Just installed version 6.0.10 and encountered the same.
