### ISSUE TITLE
Add emoticons to table upon installation

### ISSUE THREAD

**Issue by Pinkeltje** [Kunena/Kunena-Forum#9724]
**Is your feature request related to a problem? Please describe.**
Upon installation table kunena_smileys is empty. It can be solved by installing sample data

**Describe the solution you'd like**
Add records upon installation. In my opinion it shouldn't be necessary to install sample data to load smileys/emoticons

[https://www.kunena.org/forum/installation-issues/168526-emoticons-smileys-not-working-adding-new-emoticons-do-not-appear](url)

**Comment by rich20** [comment]
Not only smileys, but also the ranks are missing without sample data.

**Comment by xillibit** [comment]
Should be fixed now with my commit : https://github.com/Kunena/Kunena-Forum/commit/59b323a2d2b977904192968f02b4556b51981af4

**Comment by Pinkeltje** [comment]
Tested succesfully. Thx!

**Comment by RakhmetKotlin** [comment]
HI. It seems wrong to me. Emoticons have wrong code associated with them. For example (4, ':-(', '4.png', 'sad-grey.png', 1). 
4.png should be :P instead of :-( and other emoticons messed up as well

Also rankdisabled and rank0 not INSERTED into database. Why ?
In my Kunena download package I dont have grey emoticons png. None of 23. Where are they ?

Also all browsers seems adopted using HTML Emojis so why we still using old pngs ? We can use this instead
😭🥞🍳🥐🎇🧨🎄🎃🎃🎃🍜🦪🍚🍛🪐🌍🌚🌞🌠☄️❄️💖

**Comment by rich20** [comment]
> In my Kunena download package I dont have grey emoticons png. None of 23. Where are they ?

The grey smileys are obsolete. You have seen these in the history when you have replied to a post. The original smileys are now displayed there in K6. 
I will write a ticket to have the ‘greylocation’ column removed from the database.

**Comment by RakhmetKotlin** [comment]
Thanks. But what about other issues. 
> Should be fixed now with my commit : [59b323a](https://github.com/Kunena/Kunena-Forum/commit/59b323a2d2b977904192968f02b4556b51981af4)
1) rankdisabled and rank0 not INSERTED into database. Why ?
2) All emoticons have wrong code associated with them. 4.png should be :P instead of :-(

**Comment by Pinkeltje** [comment]
1. You can always insert them if you want, but in my opinion they are useless. disabled is the same as banned and for what would you use rank0?
2. As far as I can see, all codes show the same emoticon as the image. So I don't understand your suggested change.
> 
B)[img]/5/media/kunena/emoticons/1.png[/img]
8)[img]/5/media/kunena/emoticons/2.png[/img]
8-)[img]/5/media/kunena/emoticons/3.png[/img]
:-([img]/5/media/kunena/emoticons/4.png[/img]
:([img]/5/media/kunena/emoticons/5.png[/img]
:sad:[img]/5/media/kunena/emoticons/6.png[/img]
![2024-09-13 Screenshot 584](https://github.com/user-attachments/assets/bb26b4a5-a528-49f0-8c32-0b69d635e5ac)

**Comment by RakhmetKotlin** [comment]
![1](https://github.com/user-attachments/assets/1fc210b7-55a4-4a45-9327-88094a3b0f68)
User can be banned on forum = rankbanned
User can be banned on site = rankdisabled
We can show different colored picture depending on this status.

rank0 - for new users who posted less than X number of messages

:) must show 1.png or 2.png because its a smiley face but it shows 8.png

**Comment by Pinkeltje** [comment]
Maybe better to create a new Issue/feature request as this one is closed and the subject is adding records to tables upon installation.
