### ISSUE TITLE
In new topic, topic icons disappear when category selected 

### ISSUE THREAD

**Issue by makitso** [Kunena/Kunena-Forum#9778]
Joomla 5.2.2
Kunena  6.3.7

When a user selects the topic category, the topic icons disappear.

**Comment by makitso** [comment]
When the icons go away, id I do a Ctl D to look at the code the icons are there.  However, if I use the browser to inspect the icons they are not there. There is some javascript that looks for the ID="iconset_topicList" and does not display the icons, perhaps the edit.js in /components/com_kunena/template/aurelia/assets/js?

**Comment by rich20** [comment]
I cannot reproduce this error. Tested with SVG, Fontawesome and Images legacy. The topic symbols are always displayed.

**Comment by makitso** [comment]
I just created a new instance, installed Joomla, Kunena, and Kunena sample data.  Problem show up for me.
![image](https://github.com/user-attachments/assets/07e9e9b5-a50d-4b16-b6b9-ba08808ec184)

![image](https://github.com/user-attachments/assets/8719b538-9fa0-4d33-b633-7d6f800cdd52)

**Comment by rich20** [comment]
Now I have found out exactly what you mean. I always opened the categories via the Index -> Category -> New Topic. Please always add how errors can be reproduced.

**To Reproduce**
1. Click on New Topic
2. Use the drop-down list to switch to another category

**Result**
Topic icons are not loaded

**Comment by Pinkeltje** [comment]
Strange. When I try to replicate this, topic icons are shown but smaller (Firefox and Chrome) K 6.3.7 and J 5.2.2
![2024-12-05 Screenshot 715](https://github.com/user-attachments/assets/a0b247ee-35fe-41a7-987d-92770135cbb6)

![2024-12-05 Screenshot 716](https://github.com/user-attachments/assets/d806be85-c17b-4c80-ba0d-db165120c23f)

**Comment by makitso** [comment]
Go to the Forum tab, select the New Topic tab.
There is a selector `<div id="iconset_topicList">` `that` some java code is looking for and it then sets the display to none.  If you change the id selector name then the icons will continue to show but smaller in size.

**Comment by Pinkeltje** [comment]
Could you try this patch?
https://github.com/Pinkeltje/Kunena-Forum/commit/5db4bbbad807bb3c68e096a5794134fb1266357a
Difficult tho reproduce as as stated before I can see the topic icons when selecting other category.
There are more minor issues with topic icons BTW.

**Comment by makitso** [comment]
I am sorry, the patch did not work on my ubuntu 22.04 test system.

**Comment by Pinkeltje** [comment]
I give up.  I can't reproduce your initial problem.

**Comment by makitso** [comment]
I am at a loss as well. I get this problem on my test joomla site (clean install joomla, kunena, sample data), and on our production sysgtem.  
I sign on to joomla, select the Forum tab, select the New Topic to display the editor. The attached file is the phpinfo from our production site.

[PHP 8.2.26 - phpinfo().pdf](https://github.com/user-attachments/files/18041112/PHP.8.2.26.-.phpinfo.pdf)

**Comment by makitso** [comment]
if i change the selector in file omponents/com_kunena/template/aurelia/layouts/topic/edit/default.php, line 314 from
<div id="iconset_topicList">
to
<div id="iconset_topicListTMP">
the problem goes away.

**Comment by Pinkeltje** [comment]
Will check tomorrow.  Mine is not fresh Joomla install,  but is fresh Kunena install in Xampp PHP 8.2.
Can reproduce it on a Kunena forum of which I am a member BTW. But there entire source code for icons is invisible when changing category.

**Comment by Pinkeltje** [comment]
??? Line 314 is
` <div id="iconset_topicList">`
Please put code between tags. Had to look in Issue source code now to see what selector you referred to.

**Comment by makitso** [comment]
So, I went back to joomla 5.2.1 kunena 6.3.6 and the problem did not exist.
I then upgraded joomla to 5.2.2 and the problem did not exist.  
I then updated kunena to 6.3.7 and the above problem now exists.

**Comment by Ruud68** [comment]
@makitso was able to reproduce (and as such fix) it: https://github.com/Kunena/Kunena-Forum/pull/9784

Can you test?

@Pinkeltje just trying to understand why it was working correct for you > are you on windows hosting?

**Comment by Pinkeltje** [comment]
@Ruud68 that must be it. Running xampp on windows.

**Comment by Ruud68** [comment]
From our friendly AI:
-------------
The behavior you are observing is likely due to differences in **case sensitivity** of the underlying file systems used by the servers. Here's a breakdown of what might be happening:

### 1. **Case-Sensitive vs. Case-Insensitive File Systems**
- **Case-Sensitive File Systems**:
  - Examples: **ext4**, **XFS** (common on Linux systems), etc.
  - These file systems treat `testx.xml` and `testX.xml` as two distinct files.
  - On servers with case-sensitive file systems, you must provide the exact filename (e.g., `testx.xml`) to access the file.
  
- **Case-Insensitive File Systems**:
  - Examples: **NTFS**, **HFS+** in macOS (case-insensitive by default), etc.
  - These file systems treat `testx.xml` and `testX.xml` as equivalent.
  - On servers with case-insensitive file systems, either filename will successfully access the file.

### 2. **Server Configuration Differences**
- **Operating System**:
  - A Linux-based server will likely use a case-sensitive file system.
  - A Windows-based server or macOS server may use a case-insensitive file system.
  
- **Web Server Software**:
  - The web server (e.g., Apache, Nginx, IIS) itself does not usually enforce case sensitivity but relies on the file system's behavior.
  
- **Virtualization**:
  - If the server is running in a container or virtual machine, the file system mounted in the container/VM can also influence this behavior.

### 3. **Best Practices to Avoid Issues**
- Always use the exact case of filenames as they exist on the server.
- Adopt a consistent naming convention for files (e.g., all lowercase).
- Test your application in environments that mimic your production setup to catch these discrepancies early.

Would you like help debugging this for your specific server setup?

**Comment by Pinkeltje** [comment]
Yep. Same result from my "friend" claude. Working on it ;-)

**Comment by Ruud68** [comment]
> @Ruud68 that must be it. Running xampp on windows.

ok, that was then also the issue with the sampledata issue not being reproducable by you :)

**Comment by makitso** [comment]
@Ruud68 
Yes, this solves my original issue.
